//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi()
        {
            this.ChiTietDeThis = new HashSet<ChiTietDeThi>();
            this.DapAns = new HashSet<DapAn>();
        }
    
        public int ID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> ID_DoKho { get; set; }
        public Nullable<int> ID_MonHoc { get; set; }
        public Nullable<int> ID_LoaiCauHoi { get; set; }
        public string MaCauHoi { get; set; }
    
        public virtual DoKho DoKho { get; set; }
        public virtual LoaiCauHoi LoaiCauHoi { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDeThi> ChiTietDeThis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DapAn> DapAns { get; set; }
    }
}
