//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDeThi
    {
        public int ID { get; set; }
        public int ID_DeThi { get; set; }
        public Nullable<int> ID_CauHoi { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual DeThi DeThi { get; set; }
    }
}
