//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DapAn
    {
        public int ID { get; set; }
        public Nullable<int> ID_CauHoi { get; set; }
        public string TenDapAn { get; set; }
        public string NoiDungDapAn { get; set; }
        public Nullable<bool> DapAnDung { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
