//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.ChiTietDeThis = new HashSet<ChiTietDeThi>();
        }
    
        public int ID { get; set; }
        public string MaDeThi { get; set; }
        public string TenDeThi { get; set; }
        public Nullable<System.DateTime> NgayDeThi { get; set; }
        public Nullable<int> ThoiGian_Phut { get; set; }
        public Nullable<int> ID_MonHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDeThi> ChiTietDeThis { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
